// Chrome settings pages and internal pages. `keywords` are extra words the
// fuzzy search matches against, so "wifi" or "cache" still finds the right page.
export const CHROME_PAGES = [
  ['Settings', 'chrome://settings', 'preferences options'],
  ['Autofill and passwords', 'chrome://settings/autofill', 'forms'],
  ['Password manager', 'chrome://password-manager/passwords', 'passwords logins credentials'],
  ['Payment methods', 'chrome://settings/payments', 'credit card cards'],
  ['Addresses', 'chrome://settings/addresses', 'autofill address'],
  ['Privacy and security', 'chrome://settings/privacy', 'tracking'],
  ['Clear browsing data', 'chrome://settings/clearBrowserData', 'cache cookies delete history clear'],
  ['Third-party cookies', 'chrome://settings/cookies', 'cookies tracking'],
  ['Site settings', 'chrome://settings/content', 'permissions sites'],
  ['Notifications', 'chrome://settings/content/notifications', 'site permissions push'],
  ['Location', 'chrome://settings/content/location', 'site permissions gps'],
  ['Camera', 'chrome://settings/content/camera', 'site permissions webcam'],
  ['Microphone', 'chrome://settings/content/microphone', 'site permissions mic audio'],
  ['Pop-ups and redirects', 'chrome://settings/content/popups', 'site permissions popup'],
  ['JavaScript', 'chrome://settings/content/javascript', 'site permissions js'],
  ['Security', 'chrome://settings/security', 'safe browsing https dns'],
  ['Performance', 'chrome://settings/performance', 'memory saver energy battery'],
  ['Appearance', 'chrome://settings/appearance', 'theme font zoom dark mode bookmarks bar'],
  ['Search engine', 'chrome://settings/search', 'google default search'],
  ['Manage search engines', 'chrome://settings/searchEngines', 'site search shortcuts keywords'],
  ['Default browser', 'chrome://settings/defaultBrowser', 'default'],
  ['On startup', 'chrome://settings/onStartup', 'startup pages restore'],
  ['Languages', 'chrome://settings/languages', 'translate spell check'],
  ['Downloads settings', 'chrome://settings/downloads', 'download location folder'],
  ['Accessibility', 'chrome://settings/accessibility', 'captions a11y'],
  ['System', 'chrome://settings/system', 'proxy hardware acceleration background'],
  ['Reset settings', 'chrome://settings/reset', 'restore defaults'],
  ['You and Google', 'chrome://settings/people', 'profile account sync'],
  ['Sync', 'chrome://settings/syncSetup', 'google account'],
  ['About Chrome', 'chrome://settings/help', 'update version'],
  ['Extensions', 'chrome://extensions', 'addons plugins'],
  ['Extension keyboard shortcuts', 'chrome://extensions/shortcuts', 'hotkeys keybindings commands'],
  ['Downloads', 'chrome://downloads', 'files'],
  ['History', 'chrome://history', 'visited'],
  ['Bookmark manager', 'chrome://bookmarks', 'favorites organize'],
  ['Experiments (flags)', 'chrome://flags', 'flags experimental features'],
  ['Version info', 'chrome://version', 'about build'],
  ['GPU info', 'chrome://gpu', 'graphics webgl'],
  ['Inspect devices', 'chrome://inspect', 'devtools remote debugging'],
].map(([title, url, keywords]) => ({ title, url, keywords }));
